---
galaxy_info:
  author: Ramona Rautenberg
  description: Role osim.services.filebeat
  company: OSISM GmbH

  license: Apache License 2.0
  min_ansible_version: 2.10.0
  platforms:
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - system

dependencies: []
